version: '3'

services:
    restapi:
        build: server/
        command: python -u api.py
        ports:
            - "5001:5000"
    website:
        build: client/
        command: python -u app.py
        ports:
            - "5002:5000"
        depends_on:
            - restapi